FROM golang:1.12.9

WORKDIR /root/

RUN apt update -y && \

apt-get -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev wget

WORKDIR $GOPATH/src

RUN git clone https://github.com/free5gc/free5gc.git && \

cd free5gc && \

git submodule update --init && \

cd $GOPATH/src/free5gc && \

go get -u github.com/sirupsen/logrus && \

chmod +x ./install_env.sh && ./install_env.sh && \

cd $GOPATH/src/free5gc/src/upf && mkdir build && cd build && cmake .. && make -j`nproc`


