FROM ubuntu:bionic

WORKDIR /root/

RUN apt update -y && \

apt-get -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev wget kmod && \

wget https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz && tar -C /usr/local -zxvf go1.12.9.linux-amd64.tar.gz && mkdir -p ~/go/{bin,pkg,src}

ENV GOPATH $HOME/go

ENV GOROOT /usr/local/go

ENV PATH $PATH:$GOPATH/bin:$GOROOT/bin

ENV GO111MODULE off

RUN go get -u github.com/sirupsen/logrus

WORKDIR $GOPATH/src

RUN git clone https://github.com/free5gc/free5gc.git && \

cd free5gc && \

git submodule update --init && \

cd $GOPATH/src/free5gc && \

chmod +x ./install_env.sh && ./install_env.sh && \

cd $GOPATH/src/free5gc/src/upf && mkdir build && cd build && cmake .. && make -j`nproc`


