apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgw-svc-pool
  namespace: open5gs
  annotations:
    danm.k8s.io/selector: '{"epc-mode":"sgw"}'
    danm.k8s.io/network: gtpc
  labels:
    epc-mode: sgw
spec:
  type: ClusterIP
  ports:
  - name: gtpc
    port: 2123
    protocol: UDP
  - name: gtpu
    port: 2152
    protocol: UDP
  selector:
    epc-mode: sgw        
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgw-deployment
  namespace: open5gs
  labels:
    epc-mode: sgw
spec:
  replicas: 1
  serviceName: "open5gs-sgw-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgw
  template:
    metadata:
      labels:
        epc-mode: sgw
    spec:
      containers:
        - name: sgw
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: Always
          command: ["open5gs-sgwd", "-c", "/open5gs/config-map/sgw.yaml"]
          volumeMounts:
            - name: open5gs-sgw-config
              mountPath: /open5gs/config-map/sgw.yaml
              subPath: "sgw.yaml"
      volumes:
        - name: open5gs-sgw-config
          configMap:
            name: open5gs-sgw-config
